### ISSUE TITLE
How to build Frequency Dictionary for other languages

### ISSUE THREAD

**Issue by njfm0001** [wolfgarbe/WordSegmentationTM#1]
Is there any guide as to how to build a frequency dictionary for other languages such as Spanish? The little instructions in the readme section do not provide enough details about how to proceed in this respect.

**Comment by wolfgarbe** [comment]
You may just download word frequency dictionaries, which can be readily consumed in WordSegmentationTM or [SymSpell](https://github.com/wolfgarbe/SymSpell) (which also contains a WordSegmentation method) from here:
https://github.com/hermitdave/FrequencyWords
https://github.com/hermitdave/FrequencyWords/tree/master/content/2018/es  (Spanish)

If you want to build them yourself you may use the Google Ngram frequency lists available for many languages including Spanish. As Google Ngram contains also spelling errors, intersect this with a second dictionary which contains only genuine Spanish Words without spelling errors (e.g. a Hunspell-Dictionary https://github.com/wooorm/dictionaries/blob/master/dictionaries/es/index.dic in Spanish).

So essentially you are using only those words which occur in both lists: you use the word frequency from Google Ngrams, and the information that this is a genuine Spanish word from the Hunspell Dictionary.

To efficiently intersect two lists you can either work with hash set/dictionaries or use the merge algorithm: https://en.wikipedia.org/wiki/Merge_algorithm

**Comment by njfm0001** [comment]
This was very helpful, thank you very much!
